description: The RealtorRecommendationMonitor is a Yeager Workflow that continuously
  monitors targeted Facebook groups for posts related to real estate recommendations
  using the provided Facebook API credentials. Upon detecting a relevant post, the
  workflow extracts the user's name and phone number using the Melissa API, and sends
  a message to the user using the specified messaging platform credentials. The workflow
  returns the sent message status, as well as the extracted user name and phone number.
input-class: RealtorRecommendationMonitorIn
name: RealtorRecommendationMonitor
output-class: RealtorRecommendationMonitorOut
parameters: {}
